name:  build-ci

on:
 # workflow_run:
#    workflows: ["CodeQL"]
  #  types: 
#      - completed
  push:
    branches:
    - main
    paths: 
      - '!**/*.md'
      - '!.github/*'
  pull_request:
    branches:
    - main
    paths-ignore: 
      - '!**/*.md'
      - '!.github/*'
  
jobs:
  build:
  #  if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
