name:  .NET

on:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
  VERSION: "$(date +'%Y.%m.%d').${{github.run_number}}"
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: echo verison
      run: echo "$VERSION"
