name:  .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: echo verison
      run: "echo $VERSION"
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      env:
        GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
        VERSION: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r) #Build Number format 
