name:  .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      set VERSION: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r) #Build Number format 
    steps:
    
    - name: echo verison
      run: echo $VERSION
    - name: echo token
      run: echo $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
