name:  .NET

on:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set Version Number
      id: VersionNumber
      run: echo "::set-output name=versionNumber::$(date +'%Y.%m.%d').${{github.run_number}}"
    - name: Echo Version Number
      run: echo "${{steps.VersionNumber.outputs.versionNumber}}"
