name:  JingetExtensionsCI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/*.md'
      - '.github/*.yml'
  pull_request:
    branches: main
    paths-ignore: 
      - '**/*.md'
      - '.github/*.yml'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set Version Number
      id: VersionNumber
      run: echo "::set-output name=versionNumber::$(date +'%Y.%m.%d').${{github.run_number}}"
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{steps.VersionNumber.outputs.versionNumber}} --no-build --output ./artifacts
    - name: Push
      run: dotnet nuget push ./artifacts/**.nupkg --api-key ${{ secrets.Nuget_GitHub_Api_Key }} --source nuget.org
