name:  .NET

on:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set Version Number
      id: VersionNumber
      run: echo "::set-output name=versionNumber::$(date +'%Y.%m.%d').${{github.run_number}}"
    - name: Echo Version Number
      run: echo "${{steps.VersionNumber.outputs.versionNumber}}"
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{steps.VersionNumber.outputs.versionNumber}} --no-build --output .
    - name: Push
      run: dotnet nuget push Jinget.Extensions.${{steps.VersionNumber.outputs.versionNumber}}.nupkg --api-key ${GITHUB_TOKEN} --source https://api.nuget.org/v3/index.json
