name:  .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: echo verison
      run: echo "${VERSION}"
      env:
        GITHUB_TOKEN: ${{ secrets.Nuget_GitHub_Api_Key }}
        VERSION: $(date +'%Y.%m.%d')$(Rev:.r) #Build Number format 
