name:  release-preview-ci

on:
  workflow_run:
    workflows: ["build-ci"]
    types: 
      - completed
  push:
    branches:
    - main
    paths: 
      - '!**/*.md'
      - '!.github/*'
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  releasePreview:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output ./artifacts
    - name: Push
      run: dotnet nuget push ./artifacts/**.${VERSION}.nupkg --source https://nuget.pkg.github.com/jinget/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_GITHUB_API_KEY }}
